apiVersion: apps/v1
kind: Deployment
metadata:
  name: karsajob-frontend
  namespace: ari
  labels:
    app: karsajob-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karsajob-frontend
  template:
    metadata:
      labels:
        app: karsajob-frontend
    spec:
      containers:
      - name: karsajob-frontend
        image: ghcr.io/arigints/karsajobs-ui:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8000