apiVersion: v1
kind: Service
metadata:
  labels:
    app: karsajob-backend
  name: karsajob-backend
  namespace: ari
spec:
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30101
  selector:
    app: karsajob-backend
  type: NodePort