apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongo-test
  namespace: ari
  labels:
    app: database
spec:
  serviceName: mongo-test
  replicas: 1
  selector:
    matchLabels:
      app: database
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - name: mongo-test
        image: mongo:4.0.8
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_ROOT_USERNAME
          - name: MONGO_INITDB_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mongo-secret
                key: MONGO_ROOT_PASSWORD
        ports:
        - containerPort: 27017
          name: mongo
        volumeMounts:
        - name: mongo-pv
          mountPath: /data/db
        - name: mongo-configmap
          mountPath: /config
        - name: mongo-secret
          mountPath: /etc/mongo-credentials
      nodeSelector:
        size: large
      volumes:
      - name: mongo-secret
        secret:
          secretName: mongo-secret
          items:
          - key: MONGO_ROOT_USERNAME
            path: admin/MONGO_ROOT_USERNAME
            mode: 0777
          - key: MONGO_ROOT_PASSWORD
            path: admin/MONGO_ROOT_PASSWORD
            mode: 0777
      - name: mongo-configmap
        configMap:
          name: mongo-configmap
          items:
          - key: mongo.conf
            path: mongo.conf
      - name: mongo-pv
        persistentVolumeClaim:
          claimName: mongo-pvc