apiVersion: v1
kind: Service
metadata:
  name: mongo-test
  labels:
    app: database
  namespace: ari
spec:
  ports:
  - port: 27017
    nodePort: 30103
  selector:
    app: database
  type: NodePort