apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service
  namespace: ari
  labels:
    app: shipping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shipping-service
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      nodeSelector:
        size: large
      containers:
      - name: shipping-service
        image: ghcr.io/arigints/shipping-service
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 3001
        # env:
        # - name: APP_PORT
        #   value: "30103"
        # - name: MONGO_HOST
        #   value: "10.30.1.214"
        # - name: MONGO_USER
        #   valueFrom:
        #     secretKeyRef:
        #       name: mongo-secret
        #       key: MONGO_ROOT_USERNAME
        # - name: MONGO_PASS
        #   valueFrom:
        #     secretKeyRef:
        #       name: mongo-secret
        #       key: MONGO_ROOT_PASSWORD